### ISSUE TITLE
mergeTheseWith

### ISSUE THREAD

**Issue by maxigit** [isomorphism/these#10]
Hi 
I think a `mergeTheseWith` function would be usefull.  It would be either

    mergeTheseWith :: (a -> b) -> (b -> b -> b) -> These a  a -> a
    mergeTheseWith f op t = mergeThese op $ mapThese f f t)

or more generic

   mergeTheseWith :: (a -> c) -> (b -> c) -> (c -> c -> c) -> These a b -> c
   mergeTheseWith l r op t = mergethese op $ map These l r t

If you like the idea, I'm happy to send a pull request.

**Comment by isomorphism** [comment]
Responding very late to this, but isn't this essentially equivalent to the `these` function, but with a more restricted type?

**Comment by maxigit** [comment]
It is indeed. I just didn't realize it ;-)

**Comment by maxigit** [comment]
The difference with `these` is `op` combines the transformed datas instead of the original one.
The example when I needed is , it to check a predicate on the result of a 'join'. This would be in SQL equivalent to `a.amount > 0 OR b.amount >0`. 
With `mergeTheseWith` the code will be `mergeTheseWith (>0) (>0) (||)` .
With `these` you'll have to repeat the predicates in the combining function (`these (>0) (>0) (\a b -> a>0 || b>0)`

**Comment by isomorphism** [comment]
Aha, of course, that does make sense.

Which variant would you prefer? (Or can you think of distinct/helpful names in order to include both?)

**Comment by maxigit** [comment]
I guess the generic one `(a -> a') -> (b -> b') -> (a' -> b' -> c) -> These a b -> c` is probably more usefull.
However the actual `mergeThese` expects a `These a a` so the name `mergeTheseWith` would probably suggests the use of `These a a` as well. Maybe you need both functions as long as you can find a name for the generic version (which should in fact probably have the combining function first (for currying reason), so the signature will `(a' -> b' -> c) -> (a -> a') -> (b -> b') -> There a b -> c`.

**Comment by isomorphism** [comment]
Well, in either case it turns it into something suitable for `mergeThese` first, as shown by the type of the combine operation. I'm inclined to the more general form purely on the basis that it's easier to get one from the other that way--the less general `mergeTheseWith` doesn't really help at all if you want the general form.

As for the argument order, I'll take whichever you prefer. Obviously the `These` value should be last, otherwise I'm not sure which would be a more likely currying.

If you want to make a pull request based on the above conversation I'll happily merge (ha, ha) it, otherwise it'll probably be a few days at least before I get around to adding it myself.

**Comment by isomorphism** [comment]
Thanks!
