### ISSUE TITLE
Phrasing Align laws in terms of symmetric lax monoidal functors

### ISSUE THREAD

**Issue by paf31** [isomorphism/these#114]
In the process of porting `Align` and its docs to PureScript, I found myself wanting to use the existing language of [lax monoidal functors](https://ncatlab.org/nlab/show/monoidal+functor) to succinctly specify the laws. It doesn't get all of the laws, but I feel like it should be possible to simplify things a bit this way (at the expense of accessibility for beginners). In any case, it seemed worth discussing more broadly, and hopefully an issue is a decent place for it.

`Align` looks like a symmetric lax monoidal functor from `(*, These)` to `(*, (,))` with some additional laws. I wonder if the extra laws could be captured using similar language?

Sorry if this is the wrong place or if this is already known, in which case please do close this.

**Comment by phadej** [comment]
ok, let's see

```
align :: (f a, f b) -> f (These a b)
```

There is no identity element, think `NonEmpty`.

We can have `semigroup-y functor` still. But then we are left with only

- associativity
- naturality

from http://hackage.haskell.org/package/semialign-1/docs/Data-Semialign.html

Symmetric- adds commutativity.

But there're more laws, which hold for everything intuitively *alignable*.

I recently added `zipWith` to `Semialign`, IMHO it makes the (laws) story quite nice, even they doesn't mention category theory terms. 

If one really wants CT, then `Semialign` is a class for https://en.wikipedia.org/wiki/Polynomial_functor_(type_theory), where container's shape is a lattice.

**Comment by paf31** [comment]
Interesting, I wasn't aware that `Align` was trying to capture the idea of polynomial functors or containers. Seems like `Representable` is also relevant here then and it might be interesting to look for `Align`s which are not `Representable`?

I'm not suggesting the laws be changed, to be clear, just that there may be some abstraction between `Functor` and `Semialign` which is useful (whether or not it ought to be separated out, it might be a useful tool for thought). Perhaps trying to define the free lax monoidal functor would be useful, because it presumably would not be polynomial and would therefore give some insight as to the usefulness of the intermediate abstraction.

**Comment by phadej** [comment]
`Representable`s are boring, as they have 1/`Unit`/() as a shape. E.g. `V2`

```haskell
data V2 a = V2 a a

type Shape   = ()
type Index _ = Bool  -- note that index is Bool, not the shape!

to (V2 t f) = exists (), \i -> if i then t else f
from ((), r) = V2 (r True) (r False)
```

and the lattice for `()` is quite boring one.

---

Almost all instances of `Semialign` aren't `Representable`, I think this library only defines instances for usual suspects: `Identity` and `(->) e`.

---

I not sure there's anything interesting between `Functor` and `Semialign`. 

Semialign gives you `zipWith` and `alignWith`. `zipWith` makes an `Applicative` (via `Zippy`), does `alignWith` make something close to `Alternative`, maybe. Feel free to research.

**Comment by paf31** [comment]
Thanks, I'll think some more about this. I'll close this so you don't have a dangling issue.

**Comment by phadej** [comment]
also `Free` doesn't satisfy the idempotency law. And that one is essential for `Semialign`. Maybe there is some structure which is not `Align`, but uses `These` a tensor, I don't know.

**Comment by phadej** [comment]
Also see https://github.com/isomorphism/these/issues/96

**Comment by masaeedu** [comment]
I think there's actually lots of interesting stuff between `Functor` and `Semialign`. In fact I think `Semialign`, `Align`, and `Unalign` are largely unnecessary except as laws only subclasses of various combinations of the following families of (op)lax monoidal functors:

```
-- Symmetric lax monoidal functors between the `(,)` and itself
class Functor f => Ap f
  where
  zip :: (f a, f b) -> f (a, b)

class Ap f => Applicative f
  where
  const :: () -> f ()

-- Symmetric lax monoidal functors between the `Either` and `(,)` monoidal structures
class Functor f => Alt f
  where
  union :: (f a, f b) -> f (Either a b)

class Alt f => Alternative f
  where
  empty :: () -> f Void

-- Symmetric oplax monoidal functors between the `Either` and `(,)` monoidal
-- structures
class Functor f => Filterable f
  where
  partition :: f (Either a b) -> (f a, f b)

trivial :: Filterable f => f Void -> ()
trivial = const ()

-- Strong monoidal functors between the `Either` and `(,)` monoidal structures
class (Filterable f, Alternative f) => CompatiblyFilterable
```

All the laws just follow directly from the definition of symmetric (op)lax monoidal functors. See for example the laws for the filterable oplax monoidal functor [here](https://github.com/masaeedu/filterable/blob/master/src/Data/Filterable.hs#L59). In an expressive enough typesystem it'd be feasible and ergonomic to just have one `MonoidalFunctor` typeclass that we plug all these tensors and forward/backwards categories into.

What this has to do with `Semialign` etc. is that you can define:

```
combine :: (Apply f, Alt f) => (f a, f b) -> f (Either (Either a b) (a, b))
combine fafb = union (union fafb, zip fafb)
```

Staring at this long enough reveals that `Either (Either a b) (a, b)` is just `These` (and vice versa). So modulo an isomorphism, `combine` seems to be a good type level substitute for `align`.

In fact, @jlavelle and I played with this a bit, and we've found that it's also a good term level substitute. For every type we've looked at so far, the manually defined `Align` instance just degenerates to the behavior of `combine` and `zero` for some `Apply` and `Alternative` instance. This holds for `ZipList`s, `Maybe`s, and `Map`s; we're going to keep working through the rest of the instances to figure out if it holds exhaustively.

Something we haven't figured out yet is a category theoretic interpretation for the additional laws `Semialign` demands (e.g. the foldable law). I feel that's saying something about the free monoid object, and how the monoidal functor acts on it, but I don't have any extremely clear ideas about this.

**Comment by phadej** [comment]
This cannot represent instance for `NonEmpty` list, can it?

**Comment by masaeedu** [comment]
@phadej I believe it can. `NonEmpty a` is basically `(a, [a])`. If we treat this as `(Identity a, ZipList [a])` for the purposes of giving it `Alt` and `Apply` instances, `combine @NonEmpty` degenerates to precisely your own implementation of `align @NonEmpty`.

Here's the `Alt` instance for `Identity` btw:

```
instance Alt Identity
  where
  (<|>) = const
```

which incidentally also makes `combine @Identity` degenerate to `align @Identity`.

**Comment by masaeedu** [comment]
Perhaps another way of looking at this is that every time you write an `align` instance by hand, we can decompose what you're doing to the overlapping parts into an `Apply` instance (discarding the disjoint parts), and what you're doing to the disjoint parts into an `Alternative` instance (using `const` for the overlapping parts). This works even for somewhat more sophisticated structures like `Tree`s.

Since my last comment we've played around with this a bit more, and I think we've found a laws-only extension that prohibits at least some "bad" combinations  of `Apply` and `Alt`.

Here are four of the possible coherence maps for monoidal functors between the structures on Hask:

```
zip :: Apply f => (f a, f b) -> f (a, b)

unzip :: Functor f => f (a, b) -> (f a, f b) -- NB: This is trivially available for all functors

union :: Alt f => (f a, f b) -> f (Either a b)

partition :: Filterable f => f (Either a b) -> (f a, f b)
```

Functors for which `zip` is an inverse of `unzip` are in some sense more structure preserving than those for which this is not the case (if we additionally had that `unzip` is an inverse of `zip`, we'd have a strong monoidal functor). For example, it's true that `zip . unzip @ZipList = id`, but not that `zip . unzip @[] = id`.

I don't know whether this one addition to the laws of monoidal functors brings us to parity with the laws for `Semialign`, this requires some investigation.

**Comment by phadej** [comment]
Again, `partition` is not definable for `NonEmpty`, yet `align`,`zip` and `repeat` are. But not `nil`.

How the abstract nonsense above explains that?

---

```haskell
combine fafb = union (union fafb, zip fafb)
```

for `[1,2]` and `['x']` would give (ala `ZipList`), I assume that `union` does `fmap Left xs ++ fmap Right ys`, as what else it could do?

```haskell
union (union fafb, zip fafb)
= union ([Left 1, Left 2, Right 'x'], [(1, 'x')]
= [Left (Left 1), Left (Left 2), Left (Right 'x'), Right (1, 'x')
~ [This 1, This 2, That 'x', These 1 'x']
```

which **is not**

```haskell
[These 1 'x', This 2]
```

What kind of `Alt ZipList` should have to give what users expect from `align` for sequence-like types?

**Comment by masaeedu** [comment]
@phadej Sorry, I'm not following what `partition` has to do with `NonEmpty`. `partition` is the inverse for `union`, but `combine` itself is not defined in terms of `partition`, it only needs `union` and `zip`. `partition` is relevant as a substitute for the `Unalign` subclass, but since `NonEmpty` doesn't have an instance for that either, I don't see the problem.

The `Alternative` class when expressed in the form of a monoidal functor is:

```
class Functor f => Alt f
  where
  union :: (f a, f b) -> f (Either a b)

class Alt f => Alternative f
  where
  empty :: () -> f Void
```

Where it's `empty` that the substitute for `nil` from the `Align` class. Perhaps I'm not understanding your objection regarding `NonEmpty`, further explanation would be appreciated.

Regarding `ZipList`, `fmap Left xs ++ fmap Right ys` is wrong. You can look at the `Alternative` instance for `ZipList`s in [the source](https://hackage.haskell.org/package/base-4.12.0.0/docs/src/Control.Applicative.html#line-137):

```
instance Alternative ZipList where
   empty = ZipList []
   ZipList xs <|> ZipList ys = ZipList (xs ++ drop (length xs) ys)
```

You can quickcheck for yourself how the results of `combine` given by `ZipList`s `Applicative` and `Alternative` compare with the results of `align`.

**Comment by masaeedu** [comment]
Perhaps you're asking how we explain in terms of the category theory that `NonEmpty` doesn't support `partition`?

We'd say that `NonEmpty` is lax monoidal between `->` under the `Either` monoidal structure and `->` under the `(,)` monoidal structure, but no more. Specifically, it's just not oplax monoidal between the same structures. This is fine, lots of functors are only lax monoidal and not oplax monoidal, and some which are are both lax and oplax monoidal have no relationship between the coherence maps.

**Comment by phadej** [comment]
This is interesting.

```haskell
> let union xs ys = Left <$> xs <!> Right <$> ys
> let combine xs ys = union (union xs ys) (liftF2 (,) xs ys)
> let mangle (Left (Left a)) = This a; mangle (Left (Right b)) = That b; mangle (Right (a,b)) = These a b
> quickCheck $ \xs ys -> fmap mangle (combine xs ys) === align (xs :: ZipList Int) (ys :: ZipList Char)
*** Failed! Falsified (after 5 tests and 5 shrinks):    
ZipList {getZipList = [0]}
ZipList {getZipList = "a"}
ZipList {getZipList = [This 0]} /= ZipList {getZipList = [These 0 'a']}

-- do we need to do reordering?
> let union xs ys = Right <$> ys <!> Left <$> xs
> let combine xs ys = union (union xs ys) (liftF2 (,) xs ys)
> quickCheck $ \xs ys -> fmap mangle (combine xs ys) === align (xs :: ZipList Int) (ys :: ZipList Char)
+++ OK, passed 100 tests.

-- but it seems to work with Maps too
> let union xs ys = Right <$> ys <!> Left <$> xs
> let combine xs ys = union (union xs ys) (liftF2 (,) xs ys)
> quickCheck $ \xs ys -> fmap mangle (combine xs ys) === align (xs :: Map Bool Int) (ys :: Map Bool Char)
+++ OK, passed 100 tests.
```

Show me the code, don't make me write it myself. Examples are important.

What extra conditions one need to forbid `[a]` `Applicative` & `Alternative` to be valid `Semialign`, `Align` and `Zip` and `Repeat`? (as `repeat /= pure` e.g. for lists)

How these laws are better what we have?  Can they be decomposed into more core points?

Also note recent issue with `NonEmptyMap`, that one cannot be `Ap` with `intersectWith`, though in `combine` the `union`s make the whole result non-empty. How that fits?

Don't make me think too hard.

**Comment by masaeedu** [comment]
> Show me the code, don't make me write it myself. Examples are important.

You're right, sorry, I'm still working on polishing up the code to be able to provide the examples. There are some experiments [here](https://github.com/jlavelle/combine-align), but it's all based on a long private chat thread so it might cause more confusion than clarity.

> *code snippet*

Yes, only one out of (at least) two possible definitions of `Alternative` for each type (the usual definition and `flip`-ed) works with a given definition of `combine`. The "programming" reason is that we want the zipped together common parts of the structure to overwrite everything but the "leftover" part of the structure.

Given most `Alternative`s in Haskell are left-biased (they act on the shared part of the structure with `const` instead of `flip const`), we've been using the following definition of `combine` to get all our results:

```
mkThese :: Either (a, b) (Either a b) -> These a b
mkThese = either (uncurry These) (either This That)

combine :: (Apply f, Alt f) => f a -> f b -> f (These a b)
combine a b = mkThese <$> union (liftF2 (,) a b) (union a b)
```

> What extra conditions one need to forbid

The overall math basically works out to saying:

> a functor `f` is alignable if it is a [near-semiring](https://en.wikipedia.org/wiki/Near-semiring) object in the near-semiring category of endofunctors on `Hask` under day convolution with `(,)` as the multiplication and day convolution with `Either` as the addition

Rather than muddying the waters more with handwaving I'll write up a full set of quickcheck laws in a repo so we can play around with various samples.

> How are these laws better?

I don't think they're better in any material sense, just a little bit less "creative". Instead of inventing the right laws to try to fit our intuition, it would be nice if we could just copy paste the laws for an existing mathematical structure, so that no creativeness or reasoning skill is required on our part.

**Comment by phadej** [comment]
> near-semiring

Or lattice?

**Comment by phadej** [comment]
FYI, it's Day convolution. Person names are always capitalized.

**Comment by masaeedu** [comment]
I think every distributive lattice is a semiring, but the converse is probably not true. So if you satisfy the distributive lattice laws you will satisfy the semiring laws, but you might exclude some valid instances.

**Comment by phadej** [comment]
zippiness and alignedness needs idempotency,

`zip xs xs = fmap (\x -> (x,x)) xs` is what makes `Zip` zippy, in addition to it being `Ap`. Also commutativity `zip xs ys = fmap swap (zip ys xs)`. Those aren't in `semiring.

If you restrict yourself to only `near-semiring`, do you get *anything* stronger than compatible `Ap` & `Alt` ?

**Comment by masaeedu** [comment]
I believe you can get the zippiness law by simply demanding the `Apply` structure to be stronger than lax monoidal. Specifically a functor can be lax semigroupal like this:

```
class Functor f => Apply f
  where
  zip :: (f a, f b) -> f (a, b)
```

but it can also be *oplax* semigroupal like this:

```
-- It turns out every functor in Haskell is oplax semigroupal in this way
unzip :: Functor f => f (a, b) -> (f a, f b)
unzip fab = (fst <$> fab, snd <$> fab)
```

and finally we can ask that one coherence map act as the retraction of the other:

```
zip . unzip = id
```

I believe this is what distinguishes "zippy" applicative functors from non-zippy ones.

**Comment by masaeedu** [comment]
Regarding idempotency, there is such a thing as an [idempotent semiring](https://ncatlab.org/nlab/show/idempotent+semiring), but what its law demands is that the additive monoid be idempotent.

Unfortunately in the model I'm talking about I believe this translates to demanding `x <|> x = x`, which doesn't seem to be the same thing as what the idempotency law in `Semialign` demands (although it does seem like it would hold for all the alternatives we're interested in).

**Comment by masaeedu** [comment]
At any rate, whether you say alignables are distributive lattices or semirings or something in between, the point is this isn't a monolithic abstraction; it arises from the interaction of two monoidal functors/functor convolution monoids that are already well understood in their own right: `Applicative` and `Alternative`. I don't think there's any cases in the library where the `align` implementation does not arise from the interaction of a particular `Apply` and `Alt`.
